version: "3.9"

services:
  vm:
    build: 
      context: ./virtual-machine
    command: -port 8084
    ports:
      - 8084:8084
      - 8085:8085
  
  parser:
      build: 
        context: ./assembler
      ports:
        - 3005:3005